kind: PersistentVolume
apiVersion: v1
metadata:
  name: elk-pv
  labels:
    name: elk-pv
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/tmp/elk"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: elasticsearch
spec:
  storageClassName: manual
  selector:
    matchLabels:
      name: elk-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi